databases:
  - name: capstonerails
    databaseName: budget_app_development
    user: luis

services:
  - type: web
    name: budget_app_development
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false