default: &default
  adapter: postgresql
  encoding: unicode
  username: luis
  password: luis123
  host: localhost

development:
  <<: *default
  database: budget_app_development

test:
  <<: *default
  database: budget_app_test

production:
  url: <%= ENV['DATABASE_URL'] %>

