default: &default
  adapter: postgresql
  encoding: unicode
  username: luis
  password: luis123
  host: localhost

development:
  <<: *default
  database: budget_app2_development

test:
  <<: *default
  database: budget_app2_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  
  
